#!/bin/sh
#
# Init Bluetooth hardware....
#
DEVICE=/dev/ttyAMA1
MAC_ADDR=aa:22:33:44:55:66

case "$1" in
  start)
        echo "Starting bluetooth..."
        rfkill block 0
        rfkill unblock 0
        brcm_patchram_plus -d --patchram /lib/firmware/ap6212/bcm43438a0.hcd --enable_hci --bd_addr $MAC_ADDR --no2bytes --tosleep 5000 $DEVICE >/dev/null 2>&1 & 
        #hciconfig hci0 up
        ;;
  stop)
        echo "Stopping bluetooth..."
        #hciconfig hci0 down
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
