#!/bin/sh
#
# Init Bluetooth hardware....
#
PID_FILE=/var/run/hciattach.pid
DEVICE=/dev/ttySAC1
MAC_ADDR=aa:22:33:44:55:66

case "$1" in
  start)
        echo "Starting bluetooth..."
        echo > /dev/ttySAC1 #Hack for false starts.
        brcm_patchram_plus --patchram /lib/firmware/ap6210/bcm20702a.hcd --bd_addr $MAC_ADDR --no2bytes --tosleep 5000 $DEVICE >/dev/null 2>&1 
	    hciattach -p $DEVICE any | tail -n 1 > $PID_FILE
        hciconfig hci0 up
        ;;
  stop)
        echo "Stopping bluetooth..."
        hciconfig hci0 down

	if [ -r $PID_FILE ]; then
		kill -9 $(cat $PID_FILE)
		rm $PID_FILE
	fi	
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
